version: '3.1'

services:
    teamcity:
        image: jetbrains/teamcity-server:2017.1.2
        volumes:
            - teamcity-server-datadir:/data/teamcity_server/datadir
            - teamcity-server-logs:/opt/teamcity/logs
        ports:
            - 10000:8111
    teamcity-agent:
        image: aspnetcore/teamcity-agent-with-compose:2017.1.2
        build: ./agent
        environment:
            SERVER_URL: http://teamcity:8111
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    web:
        restart: always
        build: ./nginx/conf/
        ports:
            - "80:80"

volumes:
    teamcity-server-datadir:
    teamcity-server-logs: